# Code generated by d2a (https://github.com/walkframe/d2a). DO NOT EDIT.
import os
from importlib import import_module

from sqlalchemy import (
    types as default_types,
    Column,
    ForeignKey,
)
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy.dialects import (
    postgresql as postgresql_types,
    mysql as mysql_types,
    oracle as oracle_types,
)
from d2a import original_types
try:
    from geoalchemy2 import types as geotypes
except ImportError:
    pass

# import finished

Base = declarative_base()

# start defining models


class ContentType(Base):
    __tablename__ = 'django_content_type'
    # __table_args__ = {'extend_existing': True}
    
    id = Column(
        postgresql_types.INTEGER(),
        primary_key=True,
        unique=True,
        nullable=False,
        autoincrement=True,
        doc='testtest',
    )
    app_label = Column(
        postgresql_types.VARCHAR(length=100),
        primary_key=False,
        unique=False,
        nullable=False,
        doc='testtest',
    )
    model = Column(
        postgresql_types.VARCHAR(length=100),
        primary_key=False,
        unique=False,
        nullable=False,
        doc='testtest',
    )


class LogEntry(Base):
    __tablename__ = 'django_admin_log'
    # __table_args__ = {'extend_existing': True}
    
    id = Column(
        postgresql_types.INTEGER(),
        primary_key=True,
        unique=True,
        nullable=False,
        autoincrement=True,
        doc='testtest',
    )
    action_time = Column(
        postgresql_types.TIMESTAMP(),
        default=import_module('django.contrib.admin.models').LogEntry.action_time.field.default,
        primary_key=False,
        unique=False,
        nullable=False,
        doc='testtest',
    )
    user_id = Column(
        postgresql_types.INTEGER(),
        ForeignKey(column='auth_user.id', ondelete='CASCADE'),
        primary_key=False,
        unique=False,
        nullable=False,
        autoincrement=True,
        doc='testtest',
    )
    content_type_id = Column(
        postgresql_types.INTEGER(),
        ForeignKey(column='django_content_type.id', ondelete='SET_NULL'),
        primary_key=False,
        unique=False,
        nullable=True,
        autoincrement=True,
        doc='testtest',
    )
    object_id = Column(
        postgresql_types.TEXT(),
        primary_key=False,
        unique=False,
        nullable=True,
        doc='testtest',
    )
    object_repr = Column(
        postgresql_types.VARCHAR(length=200),
        primary_key=False,
        unique=False,
        nullable=False,
        doc='testtest',
    )
    action_flag = Column(
        postgresql_types.SMALLINT(),
        primary_key=False,
        unique=False,
        nullable=False,
        doc='testtest',
    )
    change_message = Column(
        postgresql_types.TEXT(),
        primary_key=False,
        unique=False,
        nullable=False,
        doc='testtest',
    )
    user = relationship(
        'User',
    )
    content_type = relationship(
        'ContentType',
    )


class GroupPermissions(Base):
    __tablename__ = 'auth_group_permissions'
    # __table_args__ = {'extend_existing': True}
    
    id = Column(
        postgresql_types.INTEGER(),
        primary_key=True,
        unique=True,
        nullable=False,
        autoincrement=True,
        doc='testtest',
    )
    group_id = Column(
        postgresql_types.INTEGER(),
        ForeignKey(column='auth_group.id', ondelete='CASCADE'),
        primary_key=False,
        unique=False,
        nullable=False,
        autoincrement=True,
        doc='testtest',
    )
    permission_id = Column(
        postgresql_types.INTEGER(),
        ForeignKey(column='auth_permission.id', ondelete='CASCADE'),
        primary_key=False,
        unique=False,
        nullable=False,
        autoincrement=True,
        doc='testtest',
    )
    group = relationship(
        'Group',
    )
    permission = relationship(
        'Permission',
    )


class Group(Base):
    __tablename__ = 'auth_group'
    # __table_args__ = {'extend_existing': True}
    
    id = Column(
        postgresql_types.INTEGER(),
        primary_key=True,
        unique=True,
        nullable=False,
        autoincrement=True,
        doc='testtest',
    )
    name = Column(
        postgresql_types.VARCHAR(length=150),
        primary_key=False,
        unique=True,
        nullable=False,
        doc='testtest',
    )
    permissions = relationship(
        'Permission',
        secondary='auth_group_permissions',
    )


class Permission(Base):
    __tablename__ = 'auth_permission'
    # __table_args__ = {'extend_existing': True}
    
    id = Column(
        postgresql_types.INTEGER(),
        primary_key=True,
        unique=True,
        nullable=False,
        autoincrement=True,
        doc='testtest',
    )
    name = Column(
        postgresql_types.VARCHAR(length=255),
        primary_key=False,
        unique=False,
        nullable=False,
        doc='testtest',
    )
    content_type_id = Column(
        postgresql_types.INTEGER(),
        ForeignKey(column='django_content_type.id', ondelete='CASCADE'),
        primary_key=False,
        unique=False,
        nullable=False,
        autoincrement=True,
        doc='testtest',
    )
    codename = Column(
        postgresql_types.VARCHAR(length=100),
        primary_key=False,
        unique=False,
        nullable=False,
        doc='testtest',
    )
    content_type = relationship(
        'ContentType',
    )


class UserGroups(Base):
    __tablename__ = 'auth_user_groups'
    # __table_args__ = {'extend_existing': True}
    
    id = Column(
        postgresql_types.INTEGER(),
        primary_key=True,
        unique=True,
        nullable=False,
        autoincrement=True,
        doc='testtest',
    )
    user_id = Column(
        postgresql_types.INTEGER(),
        ForeignKey(column='auth_user.id', ondelete='CASCADE'),
        primary_key=False,
        unique=False,
        nullable=False,
        autoincrement=True,
        doc='testtest',
    )
    group_id = Column(
        postgresql_types.INTEGER(),
        ForeignKey(column='auth_group.id', ondelete='CASCADE'),
        primary_key=False,
        unique=False,
        nullable=False,
        autoincrement=True,
        doc='testtest',
    )
    user = relationship(
        'User',
    )
    group = relationship(
        'Group',
    )


class UserUserPermissions(Base):
    __tablename__ = 'auth_user_user_permissions'
    # __table_args__ = {'extend_existing': True}
    
    id = Column(
        postgresql_types.INTEGER(),
        primary_key=True,
        unique=True,
        nullable=False,
        autoincrement=True,
        doc='testtest',
    )
    user_id = Column(
        postgresql_types.INTEGER(),
        ForeignKey(column='auth_user.id', ondelete='CASCADE'),
        primary_key=False,
        unique=False,
        nullable=False,
        autoincrement=True,
        doc='testtest',
    )
    permission_id = Column(
        postgresql_types.INTEGER(),
        ForeignKey(column='auth_permission.id', ondelete='CASCADE'),
        primary_key=False,
        unique=False,
        nullable=False,
        autoincrement=True,
        doc='testtest',
    )
    user = relationship(
        'User',
    )
    permission = relationship(
        'Permission',
    )


class User(Base):
    __tablename__ = 'auth_user'
    # __table_args__ = {'extend_existing': True}
    
    id = Column(
        postgresql_types.INTEGER(),
        primary_key=True,
        unique=True,
        nullable=False,
        autoincrement=True,
        doc='testtest',
    )
    password = Column(
        postgresql_types.VARCHAR(length=128),
        primary_key=False,
        unique=False,
        nullable=False,
        doc='testtest',
    )
    last_login = Column(
        postgresql_types.TIMESTAMP(),
        primary_key=False,
        unique=False,
        nullable=True,
        doc='testtest',
    )
    is_superuser = Column(
        mysql_types.BOOLEAN(),
        default=import_module('django.contrib.auth.models').User.is_superuser.field.default,
        primary_key=False,
        unique=False,
        nullable=False,
        doc='testtest',
    )
    username = Column(
        postgresql_types.VARCHAR(length=150),
        primary_key=False,
        unique=True,
        nullable=False,
        doc='testtest',
    )
    first_name = Column(
        postgresql_types.VARCHAR(length=150),
        primary_key=False,
        unique=False,
        nullable=False,
        doc='testtest',
    )
    last_name = Column(
        postgresql_types.VARCHAR(length=150),
        primary_key=False,
        unique=False,
        nullable=False,
        doc='testtest',
    )
    email = Column(
        postgresql_types.VARCHAR(length=254),
        primary_key=False,
        unique=False,
        nullable=False,
        doc='testtest',
    )
    is_staff = Column(
        mysql_types.BOOLEAN(),
        default=import_module('django.contrib.auth.models').User.is_staff.field.default,
        primary_key=False,
        unique=False,
        nullable=False,
        doc='testtest',
    )
    is_active = Column(
        mysql_types.BOOLEAN(),
        primary_key=False,
        unique=False,
        nullable=False,
        doc='testtest',
    )
    date_joined = Column(
        postgresql_types.TIMESTAMP(),
        default=import_module('django.contrib.auth.models').User.date_joined.field.default,
        primary_key=False,
        unique=False,
        nullable=False,
        doc='testtest',
    )
    groups = relationship(
        'Group',
        secondary='auth_user_groups',
    )
    user_permissions = relationship(
        'Permission',
        secondary='auth_user_user_permissions',
    )


class Session(Base):
    __tablename__ = 'django_session'
    # __table_args__ = {'extend_existing': True}
    
    session_key = Column(
        postgresql_types.VARCHAR(length=40),
        primary_key=True,
        unique=True,
        nullable=False,
        doc='testtest',
    )
    session_data = Column(
        postgresql_types.TEXT(),
        primary_key=False,
        unique=False,
        nullable=False,
        doc='testtest',
    )
    expire_date = Column(
        postgresql_types.TIMESTAMP(),
        primary_key=False,
        unique=False,
        nullable=False,
        doc='testtest',
    )


class Author(Base):
    __tablename__ = 'author'
    # __table_args__ = {'extend_existing': True}
    
    id = Column(
        postgresql_types.INTEGER(),
        primary_key=True,
        unique=True,
        nullable=False,
        autoincrement=True,
        doc='testtest',
    )
    name = Column(
        postgresql_types.VARCHAR(length=255),
        primary_key=False,
        unique=False,
        nullable=False,
        doc='testtest',
    )
    age = Column(
        postgresql_types.SMALLINT(),
        primary_key=False,
        unique=False,
        nullable=False,
        doc='testtest',
    )
    email = Column(
        postgresql_types.VARCHAR(length=254),
        primary_key=False,
        unique=False,
        nullable=True,
        doc='testtest',
    )


class BookCategory(Base):
    __tablename__ = 'book_category'
    # __table_args__ = {'extend_existing': True}
    
    id = Column(
        postgresql_types.INTEGER(),
        primary_key=True,
        unique=True,
        nullable=False,
        autoincrement=True,
        doc='testtest',
    )
    book_id = Column(
        postgresql_types.UUID(),
        ForeignKey(column='book.id', ondelete='CASCADE'),
        primary_key=False,
        unique=False,
        nullable=False,
        doc='testtest',
    )
    category_id = Column(
        postgresql_types.INTEGER(),
        ForeignKey(column='category.id', ondelete='CASCADE'),
        primary_key=False,
        unique=False,
        nullable=False,
        autoincrement=True,
        doc='testtest',
    )
    book = relationship(
        'Book',
    )
    category = relationship(
        'Category',
    )


class Book(Base):
    __tablename__ = 'book'
    # __table_args__ = {'extend_existing': True}
    
    id = Column(
        postgresql_types.UUID(),
        default=import_module('books.models').Book.id.field.default,
        primary_key=True,
        unique=True,
        nullable=False,
        doc='testtest',
    )
    price = Column(
        postgresql_types.JSONB(),
        primary_key=False,
        unique=False,
        nullable=False,
        doc='testtest',
    )
    title = Column(
        default_types.VARCHAR(length=255),
        primary_key=False,
        unique=False,
        nullable=False,
        doc='testtest',
    )
    description = Column(
        postgresql_types.TEXT(),
        primary_key=False,
        unique=False,
        nullable=True,
        doc='testtest',
    )
    author_id = Column(
        postgresql_types.INTEGER(),
        ForeignKey(column='author.id', ondelete='SET_NULL'),
        primary_key=False,
        unique=False,
        nullable=True,
        autoincrement=True,
        doc='testtest',
    )
    content = Column(
        postgresql_types.BYTEA(),
        primary_key=False,
        unique=False,
        nullable=False,
        doc='testtest',
    )
    tags = Column(
        postgresql_types.ARRAY(item_type=postgresql_types.VARCHAR),
        primary_key=False,
        unique=False,
        nullable=False,
        doc='testtest',
    )
    author = relationship(
        'Author',
    )
    category = relationship(
        'Category',
        secondary='book_category',
        lazy='joined',
    )


class CategoryRelation(Base):
    __tablename__ = 'category_relation'
    # __table_args__ = {'extend_existing': True}
    
    id = Column(
        postgresql_types.INTEGER(),
        primary_key=True,
        unique=True,
        nullable=False,
        autoincrement=True,
        doc='testtest',
    )
    category1_id = Column(
        postgresql_types.INTEGER(),
        ForeignKey(column='category.id', ondelete='CASCADE'),
        primary_key=False,
        unique=False,
        nullable=False,
        autoincrement=True,
        doc='testtest',
    )
    category2_id = Column(
        postgresql_types.INTEGER(),
        ForeignKey(column='category.id', ondelete='CASCADE'),
        primary_key=False,
        unique=False,
        nullable=False,
        autoincrement=True,
        doc='testtest',
    )
    type = Column(
        postgresql_types.VARCHAR(length=30),
        primary_key=False,
        unique=False,
        nullable=True,
        doc='testtest',
    )
    category1 = relationship(
        'Category',
        foreign_keys=[category1_id],
    )
    category2 = relationship(
        'Category',
        foreign_keys=[category2_id],
    )


class Category(Base):
    __tablename__ = 'category'
    # __table_args__ = {'extend_existing': True}
    
    id = Column(
        postgresql_types.INTEGER(),
        primary_key=True,
        unique=True,
        nullable=False,
        autoincrement=True,
        doc='testtest',
    )
    name = Column(
        original_types.CIText(),
        primary_key=False,
        unique=False,
        nullable=False,
        doc='testtest',
    )
    created = Column(
        postgresql_types.TIMESTAMP(),
        primary_key=False,
        unique=False,
        nullable=False,
        doc='testtest',
    )
    related_coming = relationship(
        'Category',
        secondary='category_relation',
        foreign_keys=[CategoryRelation.category1_id],
    )


class Sales(Base):
    __tablename__ = 'sales'
    # __table_args__ = {'extend_existing': True}
    
    id = Column(
        postgresql_types.BIGINT(),
        primary_key=True,
        unique=True,
        nullable=False,
        autoincrement=True,
        doc='testtest',
    )
    book_id = Column(
        postgresql_types.UUID(),
        ForeignKey(column='book.id', ondelete='CASCADE'),
        primary_key=False,
        unique=False,
        nullable=False,
        doc='testtest',
    )
    sold = Column(
        postgresql_types.TIMESTAMP(),
        primary_key=False,
        unique=False,
        nullable=False,
        doc='testtest',
    )
    reservation = Column(
        postgresql_types.INTERVAL(),
        primary_key=False,
        unique=False,
        nullable=True,
        doc='testtest',
    )
    source = Column(
        postgresql_types.INET(),
        primary_key=False,
        unique=False,
        nullable=True,
        doc='testtest',
    )
    book = relationship(
        'Book',
    )


# END OF FILE
