# Code generated by d2a (https://github.com/walkframe/d2a).
# `./manage.py sqla_codegen --settings=settings.codegen --path=models_sqla_example.py` at Sun Apr 18 13:58:33 2021 UTC.

import os
from importlib import import_module

import sqlalchemy as sa
from sqlalchemy import types as default_types
from sqlalchemy.dialects import (
    postgresql as postgresql_types,
    mysql as mysql_types,
    oracle as oracle_types,
)
from sqlalchemy.ext.declarative import declarative_base
try:
    from geoalchemy2 import types as geotypes
except ImportError:
    pass

# import finished

Base = declarative_base()


class CIText(default_types.String):
    '''DO NOT DELETE THIS CLASS'''
    __visit_name__ = 'CITEXT'


def GET_DEFAULT(path):
    '''DO NOT DELETE THIS FUNCTION'''

    module_path, model_name, field_name = path.rsplit(".", 2)
    try:
        module = import_module(module_path)
        model = getattr(module, model_name)
    except (ImportError, AttributeError):
        return None

    for field in model._meta.fields:
        if field.name == field_name:
            return field.default


# start defining models



class ContentType(Base):
    __tablename__ = 'django_content_type'
    
    id = sa.Column(
        postgresql_types.INTEGER(),
        primary_key=True,
        unique=True,
        nullable=False,
        autoincrement=True,
        doc="testtest",
    )
    app_label = sa.Column(
        postgresql_types.VARCHAR(length=100),
        primary_key=False,
        unique=False,
        nullable=False,
        doc="testtest",
    )
    model = sa.Column(
        postgresql_types.VARCHAR(length=100),
        primary_key=False,
        unique=False,
        nullable=False,
        doc="testtest",
    )


class LogEntry(Base):
    __tablename__ = 'django_admin_log'
    
    id = sa.Column(
        postgresql_types.INTEGER(),
        primary_key=True,
        unique=True,
        nullable=False,
        autoincrement=True,
        doc="testtest",
    )
    action_time = sa.Column(
        postgresql_types.TIMESTAMP(),
        default=GET_DEFAULT('django.contrib.admin.models.LogEntry.action_time'),
        primary_key=False,
        unique=False,
        nullable=False,
        doc="testtest",
    )
    user_id = sa.Column(
        postgresql_types.INTEGER(),
        sa.ForeignKey(column="auth_user.id", ondelete="CASCADE"),
        primary_key=False,
        unique=False,
        nullable=False,
        autoincrement=True,
        doc="testtest",
    )
    content_type_id = sa.Column(
        postgresql_types.INTEGER(),
        sa.ForeignKey(column="django_content_type.id", ondelete="SET_NULL"),
        primary_key=False,
        unique=False,
        nullable=True,
        autoincrement=True,
        doc="testtest",
    )
    object_id = sa.Column(
        postgresql_types.TEXT(),
        primary_key=False,
        unique=False,
        nullable=True,
        doc="testtest",
    )
    object_repr = sa.Column(
        postgresql_types.VARCHAR(length=200),
        primary_key=False,
        unique=False,
        nullable=False,
        doc="testtest",
    )
    action_flag = sa.Column(
        postgresql_types.SMALLINT(),
        primary_key=False,
        unique=False,
        nullable=False,
        doc="testtest",
    )
    change_message = sa.Column(
        postgresql_types.TEXT(),
        primary_key=False,
        unique=False,
        nullable=False,
        doc="testtest",
    )
    user = sa.orm.relationship(
        'User',
        foreign_keys="[django_admin_log.c.user_id]",
        remote_side=None,
        backref="logentry",
    )
    content_type = sa.orm.relationship(
        'ContentType',
        foreign_keys="[django_admin_log.c.content_type_id]",
        remote_side=None,
        backref="logentry",
    )


class GroupPermissions(Base):
    __tablename__ = 'auth_group_permissions'
    
    id = sa.Column(
        postgresql_types.INTEGER(),
        primary_key=True,
        unique=True,
        nullable=False,
        autoincrement=True,
        doc="testtest",
    )
    group_id = sa.Column(
        postgresql_types.INTEGER(),
        sa.ForeignKey(column="auth_group.id", ondelete="CASCADE"),
        primary_key=False,
        unique=False,
        nullable=False,
        autoincrement=True,
        doc="testtest",
    )
    permission_id = sa.Column(
        postgresql_types.INTEGER(),
        sa.ForeignKey(column="auth_permission.id", ondelete="CASCADE"),
        primary_key=False,
        unique=False,
        nullable=False,
        autoincrement=True,
        doc="testtest",
    )
    group = sa.orm.relationship(
        'Group',
        foreign_keys="[auth_group_permissions.c.group_id]",
        remote_side=None,
        backref="group_permissions",
    )
    permission = sa.orm.relationship(
        'Permission',
        foreign_keys="[auth_group_permissions.c.permission_id]",
        remote_side=None,
        backref="group_permissions",
    )


class Group(Base):
    __tablename__ = 'auth_group'
    
    id = sa.Column(
        postgresql_types.INTEGER(),
        primary_key=True,
        unique=True,
        nullable=False,
        autoincrement=True,
        doc="testtest",
    )
    name = sa.Column(
        postgresql_types.VARCHAR(length=150),
        primary_key=False,
        unique=True,
        nullable=False,
        doc="testtest",
    )
    permissions = sa.orm.relationship(
        'Permission',
        secondary="auth_group_permissions",
        foreign_keys="[auth_group_permissions.c.group_id, auth_group_permissions.c.permission_id]",
        remote_side=None,
        backref="group",
    )


class Permission(Base):
    __tablename__ = 'auth_permission'
    
    id = sa.Column(
        postgresql_types.INTEGER(),
        primary_key=True,
        unique=True,
        nullable=False,
        autoincrement=True,
        doc="testtest",
    )
    name = sa.Column(
        postgresql_types.VARCHAR(length=255),
        primary_key=False,
        unique=False,
        nullable=False,
        doc="testtest",
    )
    content_type_id = sa.Column(
        postgresql_types.INTEGER(),
        sa.ForeignKey(column="django_content_type.id", ondelete="CASCADE"),
        primary_key=False,
        unique=False,
        nullable=False,
        autoincrement=True,
        doc="testtest",
    )
    codename = sa.Column(
        postgresql_types.VARCHAR(length=100),
        primary_key=False,
        unique=False,
        nullable=False,
        doc="testtest",
    )
    content_type = sa.orm.relationship(
        'ContentType',
        foreign_keys="[auth_permission.c.content_type_id]",
        remote_side=None,
        backref="permission",
    )


class UserGroups(Base):
    __tablename__ = 'auth_user_groups'
    
    id = sa.Column(
        postgresql_types.INTEGER(),
        primary_key=True,
        unique=True,
        nullable=False,
        autoincrement=True,
        doc="testtest",
    )
    user_id = sa.Column(
        postgresql_types.INTEGER(),
        sa.ForeignKey(column="auth_user.id", ondelete="CASCADE"),
        primary_key=False,
        unique=False,
        nullable=False,
        autoincrement=True,
        doc="testtest",
    )
    group_id = sa.Column(
        postgresql_types.INTEGER(),
        sa.ForeignKey(column="auth_group.id", ondelete="CASCADE"),
        primary_key=False,
        unique=False,
        nullable=False,
        autoincrement=True,
        doc="testtest",
    )
    user = sa.orm.relationship(
        'User',
        foreign_keys="[auth_user_groups.c.user_id]",
        remote_side=None,
        backref="user_groups",
    )
    group = sa.orm.relationship(
        'Group',
        foreign_keys="[auth_user_groups.c.group_id]",
        remote_side=None,
        backref="user_groups",
    )


class UserUserPermissions(Base):
    __tablename__ = 'auth_user_user_permissions'
    
    id = sa.Column(
        postgresql_types.INTEGER(),
        primary_key=True,
        unique=True,
        nullable=False,
        autoincrement=True,
        doc="testtest",
    )
    user_id = sa.Column(
        postgresql_types.INTEGER(),
        sa.ForeignKey(column="auth_user.id", ondelete="CASCADE"),
        primary_key=False,
        unique=False,
        nullable=False,
        autoincrement=True,
        doc="testtest",
    )
    permission_id = sa.Column(
        postgresql_types.INTEGER(),
        sa.ForeignKey(column="auth_permission.id", ondelete="CASCADE"),
        primary_key=False,
        unique=False,
        nullable=False,
        autoincrement=True,
        doc="testtest",
    )
    user = sa.orm.relationship(
        'User',
        foreign_keys="[auth_user_user_permissions.c.user_id]",
        remote_side=None,
        backref="user_user_permissions",
    )
    permission = sa.orm.relationship(
        'Permission',
        foreign_keys="[auth_user_user_permissions.c.permission_id]",
        remote_side=None,
        backref="user_user_permissions",
    )


class User(Base):
    __tablename__ = 'auth_user'
    
    id = sa.Column(
        postgresql_types.INTEGER(),
        primary_key=True,
        unique=True,
        nullable=False,
        autoincrement=True,
        doc="testtest",
    )
    password = sa.Column(
        postgresql_types.VARCHAR(length=128),
        primary_key=False,
        unique=False,
        nullable=False,
        doc="testtest",
    )
    last_login = sa.Column(
        postgresql_types.TIMESTAMP(),
        primary_key=False,
        unique=False,
        nullable=True,
        doc="testtest",
    )
    is_superuser = sa.Column(
        mysql_types.BOOLEAN(),
        default=GET_DEFAULT('django.contrib.auth.models.User.is_superuser'),
        primary_key=False,
        unique=False,
        nullable=False,
        doc="testtest",
    )
    username = sa.Column(
        postgresql_types.VARCHAR(length=150),
        primary_key=False,
        unique=True,
        nullable=False,
        doc="testtest",
    )
    first_name = sa.Column(
        postgresql_types.VARCHAR(length=150),
        primary_key=False,
        unique=False,
        nullable=False,
        doc="testtest",
    )
    last_name = sa.Column(
        postgresql_types.VARCHAR(length=150),
        primary_key=False,
        unique=False,
        nullable=False,
        doc="testtest",
    )
    email = sa.Column(
        postgresql_types.VARCHAR(length=254),
        primary_key=False,
        unique=False,
        nullable=False,
        doc="testtest",
    )
    is_staff = sa.Column(
        mysql_types.BOOLEAN(),
        default=GET_DEFAULT('django.contrib.auth.models.User.is_staff'),
        primary_key=False,
        unique=False,
        nullable=False,
        doc="testtest",
    )
    is_active = sa.Column(
        mysql_types.BOOLEAN(),
        default=GET_DEFAULT('django.contrib.auth.models.User.is_active'),
        primary_key=False,
        unique=False,
        nullable=False,
        doc="testtest",
    )
    date_joined = sa.Column(
        postgresql_types.TIMESTAMP(),
        default=GET_DEFAULT('django.contrib.auth.models.User.date_joined'),
        primary_key=False,
        unique=False,
        nullable=False,
        doc="testtest",
    )
    groups = sa.orm.relationship(
        'Group',
        secondary="auth_user_groups",
        foreign_keys="[auth_user_groups.c.user_id, auth_user_groups.c.group_id]",
        remote_side=None,
        backref="user",
    )
    user_permissions = sa.orm.relationship(
        'Permission',
        secondary="auth_user_user_permissions",
        foreign_keys="[auth_user_user_permissions.c.user_id, auth_user_user_permissions.c.permission_id]",
        remote_side=None,
        backref="user",
    )


class Session(Base):
    __tablename__ = 'django_session'
    
    session_key = sa.Column(
        postgresql_types.VARCHAR(length=40),
        primary_key=True,
        unique=True,
        nullable=False,
        doc="testtest",
    )
    session_data = sa.Column(
        postgresql_types.TEXT(),
        primary_key=False,
        unique=False,
        nullable=False,
        doc="testtest",
    )
    expire_date = sa.Column(
        postgresql_types.TIMESTAMP(),
        primary_key=False,
        unique=False,
        nullable=False,
        doc="testtest",
    )


class Author(Base):
    __tablename__ = 'author'
    
    id = sa.Column(
        postgresql_types.INTEGER(),
        primary_key=True,
        unique=True,
        nullable=False,
        autoincrement=True,
        doc="testtest",
    )
    name = sa.Column(
        postgresql_types.VARCHAR(length=255),
        primary_key=False,
        unique=False,
        nullable=False,
        doc="testtest",
    )
    age = sa.Column(
        postgresql_types.SMALLINT(),
        primary_key=False,
        unique=False,
        nullable=False,
        doc="testtest",
    )
    email = sa.Column(
        postgresql_types.VARCHAR(length=254),
        primary_key=False,
        unique=False,
        nullable=True,
        doc="testtest",
    )


class BookCategory(Base):
    __tablename__ = 'book_category'
    
    id = sa.Column(
        postgresql_types.INTEGER(),
        primary_key=True,
        unique=True,
        nullable=False,
        autoincrement=True,
        doc="testtest",
    )
    book_id = sa.Column(
        postgresql_types.UUID(),
        sa.ForeignKey(column="book.id", ondelete="CASCADE"),
        primary_key=False,
        unique=False,
        nullable=False,
        doc="testtest",
    )
    category_id = sa.Column(
        postgresql_types.INTEGER(),
        sa.ForeignKey(column="category.id", ondelete="CASCADE"),
        primary_key=False,
        unique=False,
        nullable=False,
        autoincrement=True,
        doc="testtest",
    )
    book = sa.orm.relationship(
        'Book',
        foreign_keys="[book_category.c.book_id]",
        remote_side=None,
        backref="book_category",
    )
    category = sa.orm.relationship(
        'Category',
        foreign_keys="[book_category.c.category_id]",
        remote_side=None,
        backref="book_category",
    )


class Book(Base):
    __tablename__ = 'book'
    
    id = sa.Column(
        postgresql_types.UUID(),
        default=GET_DEFAULT('books.models.Book.id'),
        primary_key=True,
        unique=True,
        nullable=False,
        doc="testtest",
    )
    price = sa.Column(
        postgresql_types.JSONB(),
        primary_key=False,
        unique=False,
        nullable=False,
        doc="testtest",
    )
    title = sa.Column(
        default_types.VARCHAR(length=255, collation="utf8"),
        primary_key=False,
        unique=False,
        nullable=False,
        doc="testtest",
        server_default="val",
    )
    description = sa.Column(
        postgresql_types.TEXT(),
        primary_key=False,
        unique=False,
        nullable=True,
        doc="testtest",
    )
    author_id = sa.Column(
        postgresql_types.INTEGER(),
        sa.ForeignKey(column="author.id", ondelete="SET_NULL"),
        primary_key=False,
        unique=False,
        nullable=True,
        autoincrement=True,
        doc="testtest",
    )
    content = sa.Column(
        postgresql_types.BYTEA(),
        primary_key=False,
        unique=False,
        nullable=False,
        doc="testtest",
    )
    tags = sa.Column(
        postgresql_types.ARRAY(item_type=postgresql_types.VARCHAR, dimensions=1),
        primary_key=False,
        unique=False,
        nullable=False,
        doc="testtest",
    )
    author = sa.orm.relationship(
        'Author',
        foreign_keys="[book.c.author_id]",
        remote_side=None,
        backref="books",
    )
    category = sa.orm.relationship(
        'Category',
        secondary="book_category",
        foreign_keys="[book_category.c.book_id, book_category.c.category_id]",
        remote_side=None,
        backref="books",
        lazy="joined",
    )


class CategoryRelation(Base):
    __tablename__ = 'category_relation'
    
    id = sa.Column(
        postgresql_types.INTEGER(),
        primary_key=True,
        unique=True,
        nullable=False,
        autoincrement=True,
        doc="testtest",
    )
    category1_id = sa.Column(
        postgresql_types.INTEGER(),
        sa.ForeignKey(column="category.id", ondelete="CASCADE"),
        primary_key=False,
        unique=False,
        nullable=False,
        autoincrement=True,
        doc="testtest",
    )
    category2_id = sa.Column(
        postgresql_types.INTEGER(),
        sa.ForeignKey(column="category.id", ondelete="CASCADE"),
        primary_key=False,
        unique=False,
        nullable=False,
        autoincrement=True,
        doc="testtest",
    )
    type = sa.Column(
        postgresql_types.VARCHAR(length=30),
        primary_key=False,
        unique=False,
        nullable=True,
        doc="testtest",
    )
    category1 = sa.orm.relationship(
        'Category',
        foreign_keys="[category_relation.c.category1_id]",
        remote_side=None,
        backref="parents",
    )
    category2 = sa.orm.relationship(
        'Category',
        foreign_keys="[category_relation.c.category2_id]",
        remote_side=None,
        backref="children",
    )


class Category(Base):
    __tablename__ = 'category'
    
    id = sa.Column(
        postgresql_types.INTEGER(),
        primary_key=True,
        unique=True,
        nullable=False,
        autoincrement=True,
        doc="testtest",
    )
    name = sa.Column(
        CIText(),
        primary_key=False,
        unique=False,
        nullable=False,
        doc="testtest",
    )
    created = sa.Column(
        postgresql_types.TIMESTAMP(),
        primary_key=False,
        unique=False,
        nullable=False,
        doc="testtest",
    )
    related_coming = sa.orm.relationship(
        'Category',
        secondary="category_relation",
        foreign_keys="[category_relation.c.category1_id]",
        remote_side="[category.c.id]",
        backref="related_going",
    )


class Sales(Base):
    __tablename__ = 'sales'
    
    id = sa.Column(
        postgresql_types.BIGINT(),
        primary_key=True,
        unique=True,
        nullable=False,
        autoincrement=True,
        doc="testtest",
    )
    book_id = sa.Column(
        postgresql_types.UUID(),
        sa.ForeignKey(column="book.id", ondelete="CASCADE"),
        primary_key=False,
        unique=False,
        nullable=False,
        doc="testtest",
    )
    sold = sa.Column(
        postgresql_types.TIMESTAMP(),
        primary_key=False,
        unique=False,
        nullable=False,
        doc="testtest",
    )
    reservation = sa.Column(
        postgresql_types.INTERVAL(),
        primary_key=False,
        unique=False,
        nullable=True,
        doc="testtest",
    )
    source = sa.Column(
        postgresql_types.INET(),
        primary_key=False,
        unique=False,
        nullable=True,
        doc="testtest",
    )
    book = sa.orm.relationship(
        'Book',
        foreign_keys="[sales.c.book_id]",
        remote_side=None,
        backref="sales",
    )


# END OF FILE
